name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev && sh ./install_glad.sh && ./premake_linux.sh
    - name: make debug
      run: make config=debug
    - name: make release
      run: make config=release
