name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        config: [debug, release]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: sudo apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev python3-setuptools && sh ./install_glad.sh && ./premake_linux.sh
    - name: build
      run: make clean && make -j4 config=${{ matrix.config }}
  
  windows-build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019]
        config: [Debug, Release]

    steps:
    - uses: microsoft/setup-msbuild@v1.0.0
    - uses: actions/checkout@v2
    - name: configure
      run: setx path "%path%;C:\msys64" && bash -l -c "sh ./install_glad.sh" && bash -l -c "sh ./premake_vs2019.sh"
    - name: build
      run: MSBuild helios.sln /p:Configuration=${{ matrix.config }} /p:Platform=x64 /m
