name: Linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cpp-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        config: [debug, release]

    steps:
      - uses: actions/checkout@v2
      - name: artifacts cache
        id: artifact-cache
        uses: actions/cache@v2
        with:
          path: bin
          key: ${{ matrix.os }}-${{ matrix.config }}-artifact-cache
      - name: configure
        run: sudo apt-get install -y libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev python3-setuptools && sh ./install_glad.sh && ./premake_linux.sh
      - name: clean
        run: rm -rf bin bin-int && make clean
      - name: build
        run: make config=${{ matrix.config }} -j $(nproc)
